apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
  labels:
    # Ce label est OBLIGATOIRE pour que ton Prometheus 
    # (qui a le label instance=monitoring) accepte de lire ce moniteur.
    release: monitoring 
spec:
  selector:
    matchLabels:
      # On utilise les labels EXACTS que tu as vus dans ton "kubectl get svc"
      app.kubernetes.io/name: diiage-finals-app
      app.kubernetes.io/instance: backend-app
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
